### ISSUE TITLE
Error: "{ account: [ 'This field is required.' ] }"

### ISSUE THREAD

**Issue by brycelund** [aurbano/robinhood-node#24] opened 2016-04-29 17:11 UTC
Code being executed:

```js

var Robinhood = require('../src/robinhood');

var options = {
    bid_price: "3.66",
    quantity: "1",
    instrument: {
        url: "https://api.robinhood.com/instruments/ff32040e-70d7-4357-9e97-edac4a8c2cdc/",
        symbol: "SID"
    }
}


var rh = Robinhood({username:'username', password:'password'}, function(){

	rh.place_buy_order(options, function(error, response, body){
		console.log(body);
	});

});


```

According to the docs and the things I've read, this is the correct way to authenticate, yet I still get the error "{ account: [ 'This field is required.' ] }" when I run the above code. Any ideas?

**Comment by Michaeljurado24** [comment] 2016-05-01 16:27
Thanks for asking I have been trying to get this to work for a solid week!

**Comment by busse** [comment] 2016-05-01 21:39
I have determined the cause:

See line 95, `_private.account = body.account;`

https://github.com/aurbano/robinhood-node/blob/master/src/robinhood.js#L95

```javascript

  function _login(callback){
    _request.post({
      uri: _endpoints.login,
      form: {
        password: _private.password,
        username: _private.username
      }
    }, function(err, httpResponse, body) {
      if(err) {
        throw (err);
      }

      _private.account = body.account;
      _private.auth_token = body.token;
      _private.headers.Authorization = 'Token ' + _private.auth_token;

      _setHeaders();

      callback.call();
    });
  }
```
The API is not returning `account` on a call to `login` -- it only returns `token` thus `_private.account` remains unset.

The call to the `orders` API expects `account` in the body params, returning the error you (and I) are getting.

Accounts can be found buy calling `api.accounts` -- orders then expects the entire account URL, with trailing slash, similar to how the `instrument` url is used, but this time of course in the body.

I have resolved this in my local copy by setting line 95 to:

```javascript
_private.account = 'https://api.robinhood.com/accounts/ABCD1234/';
```

...where `ABCD1234` is of course my account number.

I plan to work on resolving this in a better way in my local copy, and will submit a PR once I get to that.

Amusingly, I now how a queued gfd order here on Sunday afternoon:

```javascript
{ updated_at: '2016-05-01T21:20:59.178639Z',
       ref_id: null,
       time_in_force: 'gfd',
       fees: '0.00',
       cancel: 'https://api.robinhood.com/orders/XXXXXXXXXXXX/cancel/',
       id: 'XXXXXXXXXXXX',
       cumulative_quantity: '0.00000',
       stop_price: null,
       reject_reason: null,
       instrument: 'https://api.robinhood.com/instruments/f3acdd2f-6580-4c75-a69c-81481cc4c235/',
       state: 'queued',
       trigger: 'immediate',
       type: 'market',
       last_transaction_at: '2016-05-01T21:20:59.078269Z',
       price: '14.89000000',
       executions: [],
       account: 'https://api.robinhood.com/accounts/ABCD1234/',
       url: 'https://api.robinhood.com/orders/XXXXXXXXXXXX/',
       created_at: '2016-05-01T21:20:59.078269Z',
       side: 'buy',
       position: 'https://api.robinhood.com/accounts/ABCD1234/positions/XXXXXXXXXXXX/',
       average_price: null,
       quantity: '3.00000' }
```

**Comment by aurbano** [comment] 2016-05-04 08:32
@busse oh that's interesting, thanks for digging into it. When I started this I believe the account number was returned during login but I'm not 100% sure now.

If you find a better way a PR would be wonderful, thanks!

**Closed** 2016-05-22 18:16 UTC
