### ISSUE TITLE
Update request headers passed to the latest versions

### ISSUE THREAD

**Issue by nodesocket** [aurbano/robinhood-node#17] opened 2016-02-29 07:35 UTC
Is https://github.com/aurbano/robinhood-node/blob/master/src/robinhood.js#L61 and https://github.com/aurbano/robinhood-node/blob/master/src/robinhood.js#L63 the latest versions still?

I'm showing the current version in the OS X app store is `5.5.2`, but can't see if the header `X-Robinhood-API-Version` is `1.0.0` still.

**Comment by aurbano** [comment] 2016-02-29 09:39
If you can intercept network calls that would be the best way to check the API version.

As I mentioned in other issues I moved to the UK and they still don't operate here so I can't check any further..

**Comment by swimclan** [comment] 2017-08-03 01:19
When I asked support about why some of my orders never get out of the `placed` state, they said they thought I was using an old version of the app.  I can see that this header references iOS 7 and build 823 of the app.  I think we need to somehow get the latest build number and reference iOS 10.3. 

Here is what is currently referenced in the wrapper:

`'User-Agent': 'Robinhood/823 (iPhone; iOS 7.1.2; Scale/2.00)'`

**Comment by swimclan** [comment] 2017-08-03 01:29
I used a debugging proxy to intercept the network calls being made by the app from my iOS device.  Here is what the user-agent looked like:

`User-Agent: Robinhood/5.32.0 (com.robinhood.release.Robinhood; build:3814; iOS 10.3.3) Alamofire/4.2.0 user:a8a2d71f-e82b-4ad7-8dc3-9838be7c6e7c`

I will test this then make a PR if it works

**Comment by qrpike** [comment] 2017-08-04 14:32
@swimclan Hope you get this working!

**Comment by aurbano** [comment] 2017-08-04 15:14
@qrpike I think he already did, as he submitted the PR and I've merged it. Give it a go with the latest version v1.0.0

**Closed by aurbano** 2017-08-04 15:14 UTC
Labels: question

**Comment by rclai** [comment] 2017-11-24 04:19
Are these headers necessary? I've been testing by creating limit orders in after hours (-9am & +6pm) and was able to go from unconfirmed to queued and then cancelling afterwards.

**Comment by swimclan** [comment] 2017-11-24 14:11
I was attempting to send requests without the api version number and was getting an error.  But this may have changed since then.

**Comment by rclai** [comment] 2017-11-24 17:00
Yeah it has, I created a test limit order and it filled just fine without these headers.
